name: mxlive
description: Professional M3U Live Streaming App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # নেটওয়ার্কিং এবং পার্সিং
  http: ^1.2.1
  # ভিডিও প্লেয়ার (লেটেস্ট)
  video_player: ^2.8.6
  chewie: ^1.8.1
  # ডিজাইন ও ইউটিলিটি
  google_fonts: ^6.2.1
  marquee: ^2.2.3
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.6
  # আইকন জেনারেটর (অটোমেটিক)
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
